version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src/api:/go/src/api
    networks:
      - shupple
  db:
    build: ./docker/db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: shupple
      MYSQL_USER: shupple
      MYSQL_ROOT_PASSWORD: shupple
      MYSQL_PASSWORD: shupple
    ports: 
      - "3306:3306"
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
    networks:
      - shupple
networks:
  shupple:
    external: true