name: Go
on:
  pull_request:
    branches:
    - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        go get -u github.com/gin-gonic/gin
        go get -u github.com/jinzhu/gorm
        go get -u github.com/go-sql-driver/mysql
        go get -u gopkg.in/go-playground/validator.v9
        go get -u github.com/aws/aws-sdk-go
        go get -u github.com/kelseyhightower/envconfig

    - name: Build
      run: go build -v .
